--------------------------------------------------------
--  File created - Wednesday-July-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXSO_M_ANALYSIS
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_ANALYSIS" 
   (	"R12_NUMBER" VARCHAR2(20 BYTE), 
	"SPEC" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_CLSCANVARIANT
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_CLSCANVARIANT" 
   (	"QUOTE_NUMBER" NUMBER, 
	"CUSTOMER_NUMBER" NUMBER, 
	"EFFECTIVE_DATE" NUMBER, 
	"DATE_QUOTE_EXPIRE" NUMBER, 
	"CUSTOMER_NAME" NVARCHAR2(255), 
	"ITEM" NVARCHAR2(255), 
	"ITEM_DESCRIPTION" NVARCHAR2(255), 
	"FASSON_PRICE_ONLY" NUMBER, 
	"FASSON_PRICE_PQS_ONLY_1" NUMBER, 
	"FASSON_PRICE_PQS_ONLY_2" NUMBER, 
	"FASSON_PRICE_PQS_ONLY_3" NUMBER, 
	"FASSON_PRICE_PQS_ONLY_4" NUMBER, 
	"FASSON_PRICE_PQS_ONLY_5" NUMBER, 
	"PRICE_UOM" NVARCHAR2(255), 
	"NATIONAL_ACCOUNT" NUMBER, 
	"FREIGHT_TERM" NVARCHAR2(255), 
	"MOQ" NUMBER, 
	"TRIM_FLAG" NVARCHAR2(255), 
	"MAX_TRIM_WIDTH" NUMBER, 
	"SHORT_ROLL_WAIVE" NVARCHAR2(255), 
	"CURRENCY" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_CLSUSAVARIANT
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_CLSUSAVARIANT" 
   (	"QUOTE_NUMBER" NUMBER, 
	"CUSTOMER_NUMBER" NUMBER, 
	"EFFECTIVE_DATE" NUMBER, 
	"DATE_QUOTE_EXPIRE" NUMBER, 
	"CUSTOMER_NAME" NVARCHAR2(255), 
	"ITEM" NVARCHAR2(255), 
	"ITEM_DESCRIPTION" NVARCHAR2(255), 
	"FASSON_PRICE_PQS_ONLY" NUMBER, 
	"FASSON_PRICE_PQS_ONLY_1" NUMBER, 
	"FASSON_PRICE_PQS_ONLY_2" NUMBER, 
	"FASSON_PRICE_PQS_ONLY_3" NUMBER, 
	"FASSON_PRICE_PQS_ONLY_4" NUMBER, 
	"FASSON_PRICE_PQS_ONLY_5" NUMBER, 
	"PRICE_UOM" NVARCHAR2(255), 
	"NATIONAL_ACCOUNT" NUMBER, 
	"FREIGHT_TERM" NVARCHAR2(255), 
	"MOQ" NUMBER, 
	"TRIM_FLAG" NVARCHAR2(255), 
	"MAX_TRIM_WIDTH" NUMBER, 
	"SHORT_ROLL_WAIVE" NVARCHAR2(255), 
	"CURRENCY" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_EBSITEMS
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_EBSITEMS" 
   (	"IO" VARCHAR2(20 BYTE), 
	"ITEM" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"UOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"ORDERABLE" VARCHAR2(20 BYTE), 
	"ORDER_FLAG" VARCHAR2(20 BYTE), 
	"ENABLED_FLAG" VARCHAR2(20 BYTE), 
	"CREATION_DATE" VARCHAR2(20 BYTE), 
	"LAST_UPDATE_DATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_LPMCOMPONENTCHARACT
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_LPMCOMPONENTCHARACT" 
   (	"PRODUCT_ID" NVARCHAR2(255), 
	"PRICINGFAMILY" NVARCHAR2(255), 
	"PRODUCTGROUP" NVARCHAR2(255), 
	"SPECNUMBER" NVARCHAR2(255), 
	"ITEMDESCRIPTION" NVARCHAR2(255), 
	"ITEMNUMBER" NVARCHAR2(255), 
	"ACTIVEFROM" NVARCHAR2(255), 
	"APPEARANCE" NVARCHAR2(255), 
	"CALIPER_WEIGHT" NVARCHAR2(255), 
	"COATING" NVARCHAR2(255), 
	"COMPOSITION" NVARCHAR2(255), 
	"OTHER" NVARCHAR2(255), 
	"BASE" NVARCHAR2(255), 
	"DATACAPACITY" NVARCHAR2(255), 
	"MIDPLY" NVARCHAR2(255), 
	"NFC" NVARCHAR2(255), 
	"PHARMA" NVARCHAR2(255), 
	"PRINTTECH" NVARCHAR2(255), 
	"TAMPEREVIDENT" NVARCHAR2(255), 
	"VISUALINDICATOR" NVARCHAR2(255), 
	"WELD" NVARCHAR2(255), 
	"ADHESIVEDESCRIPTION1" NVARCHAR2(255), 
	"ADHESIVEBASE1" NVARCHAR2(255), 
	"CTWT1" NVARCHAR2(255), 
	"PATTERNGUM" NVARCHAR2(255), 
	"LINERDESCRIPTION1" NVARCHAR2(255), 
	"LINERBASE1" NVARCHAR2(255), 
	"RELEASE1" NVARCHAR2(255), 
	"ADHESIVEDESCRIPTION2" NVARCHAR2(255), 
	"ADHESIVEBASE2" NVARCHAR2(255), 
	"CTWT2" NVARCHAR2(255), 
	"LAST_UPDATE_DATE" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_LPMCOMPONENTCHARACT_SRC
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_LPMCOMPONENTCHARACT_SRC" 
   (	"PRODUCT_ID" NVARCHAR2(255), 
	"PRICINGFAMILY" NVARCHAR2(255), 
	"PRODUCTGROUP" NVARCHAR2(255), 
	"SPECNUMBER" NVARCHAR2(255), 
	"ITEMDESCRIPTION" NVARCHAR2(255), 
	"ITEMNUMBER" NVARCHAR2(255), 
	"ACTIVEFROM" NVARCHAR2(255), 
	"APPEARANCE" NVARCHAR2(255), 
	"CALIPER_WEIGHT" NVARCHAR2(255), 
	"COATING" NVARCHAR2(255), 
	"COMPOSITION" NVARCHAR2(255), 
	"OTHER" NVARCHAR2(255), 
	"BASE" NVARCHAR2(255), 
	"DATACAPACITY" NVARCHAR2(255), 
	"MIDPLY" NVARCHAR2(255), 
	"NFC" NVARCHAR2(255), 
	"PHARMA" NVARCHAR2(255), 
	"PRINTTECH" NVARCHAR2(255), 
	"TAMPEREVIDENT" NVARCHAR2(255), 
	"VISUALINDICATOR" NVARCHAR2(255), 
	"WELD" NVARCHAR2(255), 
	"ADHESIVEDESCRIPTION1" NVARCHAR2(255), 
	"ADHESIVEBASE1" NVARCHAR2(255), 
	"CTWT1" NVARCHAR2(255), 
	"PATTERNGUM" NVARCHAR2(255), 
	"LINERDESCRIPTION1" NVARCHAR2(255), 
	"LINERBASE1" NVARCHAR2(255), 
	"RELEASE1" NVARCHAR2(255), 
	"ADHESIVEDESCRIPTION2" NVARCHAR2(255), 
	"ADHESIVEBASE2" NVARCHAR2(255), 
	"CTWT2" NVARCHAR2(255), 
	"LAST_UPDATE_DATE" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_LPMOTHERPRODCHARACT
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_LPMOTHERPRODCHARACT" 
   (	"PRODUCT_ID" NVARCHAR2(255), 
	"PRICINGFAMILY" NVARCHAR2(255), 
	"PRODUCTGROUP" NVARCHAR2(255), 
	"SPECNUMBER" NVARCHAR2(255), 
	"SPECDESCRIPTION" NVARCHAR2(255), 
	"ITEMNUMBER" NVARCHAR2(255), 
	"PRODUCTLINE" NVARCHAR2(255), 
	"ACTIVEFROM" NVARCHAR2(255), 
	"LINERDESCRIPTION2" NVARCHAR2(255), 
	"LINERBASE2" NVARCHAR2(255), 
	"RELEASE2" NVARCHAR2(255), 
	"MISCUPCHARGECODE" NVARCHAR2(255), 
	"MISCUPCHARGECODE2" NVARCHAR2(255), 
	"MISCUPCHARGECODE3" NVARCHAR2(255), 
	"WIDTHFAMILY" NVARCHAR2(255), 
	"BESTAVAILABLESTOCKSTATUS" NVARCHAR2(255), 
	"MANUALFLOORPRICE" NVARCHAR2(255), 
	"PRODUCTSTRATEGY" NVARCHAR2(255), 
	"PRICERESTRICTEDREASONCODE" NVARCHAR2(255), 
	"ITEM_STATUS_CODE" NVARCHAR2(255), 
	"READYFORPRICING" NVARCHAR2(255), 
	"ATTRIBUTESFILLED" NVARCHAR2(255), 
	"FLAGBLOCK" NVARCHAR2(255), 
	"ITEMUOM" NVARCHAR2(255), 
	"CONVERSTIONFACTOR" NVARCHAR2(255), 
	"LAST_UPDATE_DATE" NVARCHAR2(255), 
	"ITEMDESCRIPTION" NVARCHAR2(255), 
	"ATT11" NVARCHAR2(255), 
	"ATT21" NVARCHAR2(255), 
	"ATT23" NVARCHAR2(255), 
	"ATT29" NVARCHAR2(255), 
	"ALTERNATE_SPEC" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_LPMOTHERPRODCHARACT_SRC
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_LPMOTHERPRODCHARACT_SRC" 
   (	"PRODUCT_ID" NVARCHAR2(255), 
	"PRICINGFAMILY" NVARCHAR2(255), 
	"PRODUCTGROUP" NVARCHAR2(255), 
	"SPECNUMBER" NVARCHAR2(255), 
	"SPECDESCRIPTION" NVARCHAR2(255), 
	"PRODUCTLINE" NVARCHAR2(255), 
	"ITEMNUMBER" NVARCHAR2(255), 
	"ACTIVEFROM" NVARCHAR2(255), 
	"LINERDESCRIPTION2" NVARCHAR2(255), 
	"LINERBASE2" NVARCHAR2(255), 
	"RELEASE2" NVARCHAR2(255), 
	"MISCUPCHARGECODE" NVARCHAR2(255), 
	"MISCUPCHARGECODE2" NVARCHAR2(255), 
	"MISCUPCHARGECODE3" NVARCHAR2(255), 
	"WIDTHFAMILY" NVARCHAR2(255), 
	"BESTAVAILABLESTOCKSTATUS" NVARCHAR2(255), 
	"MANUALFLOORPRICE" NVARCHAR2(255), 
	"PRODUCTSTRATEGY" NVARCHAR2(255), 
	"PRICERESTRICTEDREASONCODE" NVARCHAR2(255), 
	"ITEM_STATUS_CODE" NVARCHAR2(255), 
	"READYFORPRICING" NVARCHAR2(255), 
	"ATTRIBUTESFILLED" NVARCHAR2(255), 
	"FLAGBLOCK" NVARCHAR2(255), 
	"ITEMUOM" NVARCHAR2(255), 
	"CONVERSIONFACTOR" NVARCHAR2(255), 
	"LAST_UPDATE_DATE" NVARCHAR2(255), 
	"ITEMDESCRIPTION" NVARCHAR2(255), 
	"ATTR11" NVARCHAR2(255), 
	"ATTR21" NVARCHAR2(255), 
	"ATTR23" NVARCHAR2(255), 
	"FREIGHTRATE" NVARCHAR2(255), 
	"ATTR30" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_LPMXREF
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_LPMXREF" 
   (	"LEGACY_ACCOUNT_NUMBER" NVARCHAR2(255), 
	"LEGACY_SYSTEM" NVARCHAR2(255), 
	"R12_PARTY_NAME" NVARCHAR2(255), 
	"R12_CUST_ACCT_NUMBER" NVARCHAR2(255), 
	"R12_PARTY_NUMBER" NVARCHAR2(255), 
	"LEGACY_ACTIVE_FLAG" NVARCHAR2(255), 
	"LEGACY_ACCOUNT_IDENTIFIER" NVARCHAR2(255), 
	"F8" NVARCHAR2(255), 
	"F9" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_LPMXREFNATIONALACCOUNT
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_LPMXREFNATIONALACCOUNT" 
   (	"PRICING_GROUP_NAME" NVARCHAR2(255), 
	"LEGACY_PRICING_GROUP_NUMBER" NUMBER, 
	"ORACLE_ACCOUNT_NUMBER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_MIGRATIONPROCESSERRORS
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_MIGRATIONPROCESSERRORS" 
   (	"ERRORNUMBER" NVARCHAR2(50), 
	"ERRORVALUE" NVARCHAR2(50), 
	"ERRORMESSAGE" NVARCHAR2(400)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_OUTCUSTOMERREFERENCE
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_OUTCUSTOMERREFERENCE" 
   (	"NAME" NVARCHAR2(50), 
	"VALUE" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_OUTITEMREFERENCE
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_OUTITEMREFERENCE" 
   (	"NAME" NVARCHAR2(50), 
	"VALUE" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_OUTNATIONALACCOUNTREF
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_OUTNATIONALACCOUNTREF" 
   (	"NAME" NVARCHAR2(50), 
	"VALUE" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_OUTNEGOTIATEDPABSTAGING
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_OUTNEGOTIATEDPABSTAGING" 
   (	"NATIONALACCOUNTNUMBER" NVARCHAR2(255), 
	"CUSTOMERID" NVARCHAR2(255), 
	"ACTIVE" NVARCHAR2(255), 
	"QUOTE" NVARCHAR2(255), 
	"LINEITEMID" NVARCHAR2(255), 
	"QUOTETYPE" NVARCHAR2(255), 
	"CUSTOMERNAME" NVARCHAR2(255), 
	"CUSTOMERNUMBER" NVARCHAR2(255), 
	"ITEM" NVARCHAR2(255), 
	"ITEM_TYPE" NVARCHAR2(255), 
	"BUSINESSUNIT" NVARCHAR2(255), 
	"PRICE" NUMBER, 
	"CURRENCY" NVARCHAR2(255), 
	"EFFECTIVEDATE" DATE, 
	"EXPIRYDATE" DATE, 
	"UOM" NVARCHAR2(255), 
	"FREIGHTRATES" NVARCHAR2(255), 
	"FREIGHTTERMS" NVARCHAR2(255), 
	"PROJECTNAME" NVARCHAR2(255), 
	"QUOTECOMMENT" NVARCHAR2(255), 
	"PROJECTNUMBER" NVARCHAR2(255), 
	"APPLYQTYBREAKSTR" NVARCHAR2(255), 
	"MOQ" NVARCHAR2(255), 
	"SHORTROLLWAIVE" NVARCHAR2(255), 
	"SPECDESC" NVARCHAR2(255), 
	"SPECDESC2" NVARCHAR2(255), 
	"TRIMWAIVE" NVARCHAR2(255), 
	"ATTRIBUTE27" NVARCHAR2(255), 
	"LENGTH" NVARCHAR2(255), 
	"TRIMMAX" NUMBER, 
	"QUOTESTATUS" NVARCHAR2(255), 
	"ORIGINALEXPIRATIONDATE" DATE, 
	"SYSTEMADDEDDATE" DATE, 
	"SYSTEMUPDATEREASON" NVARCHAR2(255), 
	"REASONFORMANUALPRICECHANGE" NVARCHAR2(255), 
	"PRICINGSUBGROUP" NVARCHAR2(255), 
	"QUOTEDISCOUNTPERCENTAGE" NUMBER, 
	"SHEETINGWAIVE" NVARCHAR2(255), 
	"LIFECYCLESTATUS" NVARCHAR2(255), 
	"QUOTEDESCRIPTION" NVARCHAR2(255), 
	"CUSTOMERTIERPERCENTAGE" NUMBER, 
	"UPDATEONLYTHISCUSTOMER" NVARCHAR2(255), 
	"QUOTEUNIQUEID" NVARCHAR2(255), 
	"APPROVEDBY" NVARCHAR2(255), 
	"APPROVEDDATE" DATE, 
	"NAME_WO_REVISION" NVARCHAR2(255), 
	"PRODUCTCOMMENT" NVARCHAR2(255), 
	"ATTRIBUTE48" NVARCHAR2(255), 
	"ATTRIBUTE49" NVARCHAR2(255), 
	"ATTRIBUTE50" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_OUTNEGOTIATEDPLSTAGING
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_OUTNEGOTIATEDPLSTAGING" 
   (	"NATIONALACCOUNTNUMBER" NVARCHAR2(255), 
	"CUSTOMERID" NVARCHAR2(255), 
	"ACTIVE" NVARCHAR2(255), 
	"QUOTE" NVARCHAR2(255), 
	"LINEITEMID" NVARCHAR2(255), 
	"QUOTETYPE" NVARCHAR2(255), 
	"CUSTOMERNAME" NVARCHAR2(255), 
	"CUSTOMERNUMBER" NVARCHAR2(255), 
	"ITEM" NVARCHAR2(255), 
	"ITEM_TYPE" NVARCHAR2(255), 
	"BUSINESSUNIT" NVARCHAR2(255), 
	"PRICE" NUMBER, 
	"CURRENCY" NVARCHAR2(255), 
	"EFFECTIVEDATE" DATE, 
	"EXPIRYDATE" DATE, 
	"UOM" NVARCHAR2(10), 
	"FREIGHTRATES" NVARCHAR2(255), 
	"FREIGHTTERMS" NVARCHAR2(255), 
	"PROJECTNAME" NVARCHAR2(255), 
	"QUOTECOMMENT" NVARCHAR2(255), 
	"PROJECTNUMBER" NVARCHAR2(255), 
	"APPLYQTYBREAKSTR" NVARCHAR2(255), 
	"MOQ" NVARCHAR2(255), 
	"SHORTROLLWAIVE" NVARCHAR2(255), 
	"SPECDESC" NVARCHAR2(255), 
	"SPECDESC2" NVARCHAR2(255), 
	"TRIMWAIVE" NVARCHAR2(255), 
	"ATTRIBUTE27" NVARCHAR2(255), 
	"LENGTH" NVARCHAR2(255), 
	"TRIMMAX" NUMBER, 
	"QUOTESTATUS" NVARCHAR2(255), 
	"ORIGINALEXPIRATIONDATE" DATE, 
	"SYSTEMADDEDDATE" DATE, 
	"SYSTEMUPDATEREASON" NVARCHAR2(255), 
	"REASONFORMANUALPRICECHANGE" NVARCHAR2(255), 
	"PRICINGSUBGROUP" NVARCHAR2(255), 
	"QUOTEDISCOUNTPERCENTAGE" NUMBER, 
	"SHEETINGWAIVE" NVARCHAR2(255), 
	"LIFECYCLESTATUS" NVARCHAR2(255), 
	"QUOTEDESCRIPTION" NVARCHAR2(255), 
	"CUSTOMERTIERPERCENTAGE" NUMBER, 
	"UPDATEONLYTHISCUSTOMER" NVARCHAR2(255), 
	"QUOTEUNIQUEID" NVARCHAR2(255), 
	"APPROVEDBY" NVARCHAR2(255), 
	"APPROVEDDATE" DATE, 
	"NAME_WO_REVISION" NVARCHAR2(255), 
	"PRODUCTCOMMENT" NVARCHAR2(255), 
	"ATTRIBUTE48" NVARCHAR2(255), 
	"ATTRIBUTE49" NVARCHAR2(255), 
	"ATTRIBUTE50" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_OUTP2LPMCOMPCHARACT
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_OUTP2LPMCOMPCHARACT" 
   (	"PRODUCT_ID" NVARCHAR2(255), 
	"PRICINGFAMILY" NVARCHAR2(255), 
	"PRODUCTGROUP" NVARCHAR2(255), 
	"SPECNUMBER" NVARCHAR2(255), 
	"ITEMDESCRIPTION" NVARCHAR2(255), 
	"ITEMNUMBER" NVARCHAR2(255), 
	"ACTIVEFROM" NVARCHAR2(255), 
	"APPEARANCE" NVARCHAR2(255), 
	"CALIPER_WEIGHT" NVARCHAR2(255), 
	"COATING" NVARCHAR2(255), 
	"COMPOSITION" NVARCHAR2(255), 
	"OTHER" NVARCHAR2(255), 
	"BASE" NVARCHAR2(255), 
	"DATACAPACITY" NVARCHAR2(255), 
	"MIDPLY" NVARCHAR2(255), 
	"NFC" NVARCHAR2(255), 
	"PHARMA" NVARCHAR2(255), 
	"PRINTTECH" NVARCHAR2(255), 
	"TAMPEREVIDENT" NVARCHAR2(255), 
	"VISUALINDICATOR" NVARCHAR2(255), 
	"WELD" NVARCHAR2(255), 
	"ADHESIVEDESCRIPTION_1" NVARCHAR2(255), 
	"ADHESIVEBASE_1" NVARCHAR2(255), 
	"CTWT1" NVARCHAR2(255), 
	"PATTERNGUM" NVARCHAR2(255), 
	"LINERDESCRIPTION_1" NVARCHAR2(255), 
	"LINERBASE_1" NVARCHAR2(255), 
	"RELEASE_1" NVARCHAR2(255), 
	"ADHESIVEDESCRIPTION_2" NVARCHAR2(255), 
	"ADHESIVEBASE_2" NVARCHAR2(255), 
	"CTWT2" NVARCHAR2(255), 
	"LAST_UPDATE_DATE" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_OUTP2LPMCOMPCHARACT_R
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_OUTP2LPMCOMPCHARACT_R" 
   (	"PRODUCT_ID" NVARCHAR2(255), 
	"PRICINGFAMILY" NVARCHAR2(255), 
	"PRODUCTGROUP" NVARCHAR2(255), 
	"SPECNUMBER" NVARCHAR2(255), 
	"ITEMDESCRIPTION" NVARCHAR2(255), 
	"ITEMNUMBER" NVARCHAR2(255), 
	"ACTIVEFROM" NVARCHAR2(255), 
	"APPEARANCE" NVARCHAR2(255), 
	"CALIPER_WEIGHT" NVARCHAR2(255), 
	"COATING" NVARCHAR2(255), 
	"COMPOSITION" NVARCHAR2(255), 
	"OTHER" NVARCHAR2(255), 
	"BASE" NVARCHAR2(255), 
	"DATACAPACITY" NVARCHAR2(255), 
	"MIDPLY" NVARCHAR2(255), 
	"NFC" NVARCHAR2(255), 
	"PHARMA" NVARCHAR2(255), 
	"PRINTTECH" NVARCHAR2(255), 
	"TAMPEREVIDENT" NVARCHAR2(255), 
	"VISUALINDICATOR" NVARCHAR2(255), 
	"WELD" NVARCHAR2(255), 
	"ADHESIVEDESCRIPTION_1" NVARCHAR2(255), 
	"ADHESIVEBASE_1" NVARCHAR2(255), 
	"CTWT1" NVARCHAR2(255), 
	"PATTERNGUM" NVARCHAR2(255), 
	"LINERDESCRIPTION_1" NVARCHAR2(255), 
	"LINERBASE_1" NVARCHAR2(255), 
	"RELEASE_1" NVARCHAR2(255), 
	"ADHESIVEDESCRIPTION_2" NVARCHAR2(255), 
	"ADHESIVEBASE_2" NVARCHAR2(255), 
	"CTWT2" NVARCHAR2(255), 
	"LAST_UPDATE_DATE" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_OUTP2LPMOTHERPRODCHAR
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_OUTP2LPMOTHERPRODCHAR" 
   (	"PRODUCT_ID" NVARCHAR2(255), 
	"PRICINGFAMILY" NVARCHAR2(255), 
	"PRODUCTGROUP" NVARCHAR2(255), 
	"SPECNUMBER" NVARCHAR2(255), 
	"SPECDESCRIPTION" NVARCHAR2(255), 
	"ITEMNUMBER" NVARCHAR2(255), 
	"PRODUCTLINE" NVARCHAR2(255), 
	"ACTIVEFROM" NVARCHAR2(255), 
	"LINERDESCRIPTION_2" NVARCHAR2(255), 
	"LINERBASE_2" NVARCHAR2(255), 
	"RELEASE_2" NVARCHAR2(255), 
	"MISCUPCHARGECODE" NVARCHAR2(255), 
	"MISCUPCHARGECODE2" NVARCHAR2(255), 
	"MISCUPCHARGECODE3" NVARCHAR2(255), 
	"WIDTHFAMILY" NVARCHAR2(255), 
	"BESTAVAILABLESTOCKSTATUS" NVARCHAR2(255), 
	"MANUALFLOORPRICE" NVARCHAR2(255), 
	"PRODUCTSTRATEGY" NVARCHAR2(255), 
	"PRICERESTRICTEDREASONCODE" NVARCHAR2(255), 
	"ITEM_STATUS_CODE" NVARCHAR2(255), 
	"READYFORPRICING" NVARCHAR2(255), 
	"ATTRIBUTESFILLED" NVARCHAR2(255), 
	"FLAGBLOCK" NVARCHAR2(255), 
	"ITEMUOM" NVARCHAR2(255), 
	"CONVERSTIONFACTOR" NVARCHAR2(255), 
	"LAST_UPDATE_DATE" NVARCHAR2(255), 
	"ITEMDESCRIPTION" NVARCHAR2(255), 
	"ATTR11" NVARCHAR2(255), 
	"ATTR21" NVARCHAR2(255), 
	"ATTR23" NVARCHAR2(255), 
	"ATTR29" NVARCHAR2(255), 
	"ALTERNATE_SPEC" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_OUTPRODUCTREFERENCE
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_OUTPRODUCTREFERENCE" 
   (	"NAME" NVARCHAR2(50), 
	"VALUE" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_OUTTRANSFERPRICE
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_OUTTRANSFERPRICE" 
   (	"PRODUCT_ID" VARCHAR2(50 BYTE), 
	"LIST_PRICE" NUMBER, 
	"LIST_PRICE_CAD" NUMBER, 
	"ITEM_NUMBER" VARCHAR2(50 BYTE), 
	"UOM" VARCHAR2(20 BYTE), 
	"CURRENCY" VARCHAR2(20 BYTE), 
	"START_DATE" DATE, 
	"EXPIRATION_DATE" DATE, 
	"ITEM_TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_PABEXTRACT
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_PABEXTRACT" 
   (	"CUSTOMER_NAME" NVARCHAR2(255), 
	"CUST" NVARCHAR2(255), 
	"SPEC" NVARCHAR2(255), 
	"CREATED_ON" NVARCHAR2(255), 
	"QUOTE" NVARCHAR2(255), 
	"OTO" NVARCHAR2(255), 
	"OPPORTUNITY_TYPE" NVARCHAR2(255), 
	"REQUESTED_PRICE" NVARCHAR2(255), 
	"CURRENCY_TYPE" NVARCHAR2(255), 
	"MSI_QTY" NVARCHAR2(255), 
	"COMMENTS" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_PFXCUSTOMERMASTER
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_PFXCUSTOMERMASTER" 
   (	"CUSTOMER_ID" NVARCHAR2(255), 
	"COMPANY_NAME" NVARCHAR2(255), 
	"LAST_UPDATE" NVARCHAR2(255), 
	"SFDC_IDENTIFIER" NVARCHAR2(255), 
	"CUSTOMER_NUM_CD" NVARCHAR2(255), 
	"BILL_TO_STATE_CD" NVARCHAR2(255), 
	"BILL_TO_ZIP_CD" NVARCHAR2(255), 
	"SOURCE_SYSTEM_CD" NVARCHAR2(255), 
	"SALES_DISTRICT_CD" NVARCHAR2(255), 
	"SALES_TEAM_CD" NVARCHAR2(255), 
	"SALES_TEAM_DESC" NVARCHAR2(255), 
	"NATIONAL_ACCT_NUM_CD" NVARCHAR2(255), 
	"SHIP_TO_ZIP_CD" NVARCHAR2(255), 
	"SHIP_TO_COUNTRY_DESC" NVARCHAR2(255), 
	"DISTRIBUTOR_CD" NVARCHAR2(255), 
	"CUSTOMER_STATUS_CD" NVARCHAR2(255), 
	"LPM_MEU_DESC" NVARCHAR2(255), 
	"GRS_CHANNEL_DESC" NVARCHAR2(255), 
	"DIVISION_LEVEL_CD" NVARCHAR2(255), 
	"BILL_TO_CITY_CD" NVARCHAR2(255), 
	"ACCOUNT_EXTERNAL_ID" NVARCHAR2(255), 
	"CUSTOMER_PRIORITY_CD" NVARCHAR2(255), 
	"SHIP_TO_STATE_CD" NVARCHAR2(255), 
	"BILL_TO_COUNTRY_DESC" NVARCHAR2(255), 
	"FREIGHT_TERM" NVARCHAR2(255), 
	"SHIP_TO_ADDRESS" NVARCHAR2(255), 
	"BILL_TO_ADDRESS" NVARCHAR2(255), 
	"SHIP_TO_CITY_CD" NVARCHAR2(255), 
	"ATTR26" NVARCHAR2(255), 
	"ATTR27" NVARCHAR2(255), 
	"ATTR28" NVARCHAR2(255), 
	"ATTR29" NVARCHAR2(255), 
	"ATTR30" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_PFXCUSTOMERMASTER_SRC
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_PFXCUSTOMERMASTER_SRC" 
   (	"CUSTOMER_ID" NVARCHAR2(255), 
	"COMPANY_NAME" NVARCHAR2(255), 
	"LAST_UPDATE" NVARCHAR2(255), 
	"SFDC_IDENTIFIER" NVARCHAR2(255), 
	"CUSTOMER_NUM_CD" NVARCHAR2(255), 
	"SHIP_TO_NUM_CD" NVARCHAR2(255), 
	"BILL_TO_NUM_CD" NVARCHAR2(255), 
	"SOURCE_SYSTEM_CD" NVARCHAR2(255), 
	"SALES_DISTRICT_CD" NVARCHAR2(255), 
	"SALES_TEAM_CD" NVARCHAR2(255), 
	"SALES_TEAM_DESC" NVARCHAR2(255), 
	"NATIONAL_ACCT_NUM_CD" NVARCHAR2(255), 
	"SHIP_TO_ZIP_CD" NVARCHAR2(255), 
	"SHIP_TO_COUNTRY_DESC" NVARCHAR2(255), 
	"DISTRIBUTOR_CD" NVARCHAR2(255), 
	"LPM_MEU_CD" NVARCHAR2(255), 
	"LPM_MEU_DESC" NVARCHAR2(255), 
	"GRS_CHANNEL_DESC" NVARCHAR2(255), 
	"DIVISION_LEVEL_CD" NVARCHAR2(255), 
	"SOURCE_SUB_SYSTEM_CD" NVARCHAR2(255), 
	"ACCOUNT_EXTERNAL_ID" NVARCHAR2(255), 
	"CUSTOMER_PRIORITY_CD" NVARCHAR2(255), 
	"SHIP_TO_STATE_CD" NVARCHAR2(255), 
	"DISTRIBUTOR_DESC" NVARCHAR2(255), 
	"FREIGHT_TERM" NVARCHAR2(255), 
	"CUSTOMER_STATUS_CD" NVARCHAR2(255), 
	"ATTR24" NVARCHAR2(255), 
	"ATTR25" NVARCHAR2(255), 
	"ATTR26" NVARCHAR2(255), 
	"ATTR27" NVARCHAR2(255), 
	"ATTR28" NVARCHAR2(255), 
	"ATTR29" NVARCHAR2(255), 
	"ATTR30" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_PFXITEMMASTER
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_PFXITEMMASTER" 
   (	"PRODUCT_ID" NVARCHAR2(255), 
	"SOLD_ITEM_DESC" NVARCHAR2(255), 
	"SOURCE_SYSTEM_CD" NVARCHAR2(255), 
	"SFDC_IDENTIFIER" NVARCHAR2(255), 
	"LAST_UPDATE" NVARCHAR2(255), 
	"PRICING_LOGIC" NVARCHAR2(255), 
	"SOURCE_SUB_SYSTEM_CD" NVARCHAR2(255), 
	"EXTRACT_ID" NVARCHAR2(255), 
	"SPEC_DESC" NVARCHAR2(255), 
	"SPEC_CD" NVARCHAR2(255), 
	"PROD_LINE_TEAM_CD" NVARCHAR2(255), 
	"PRESSURE_SENSITIVE" NVARCHAR2(255), 
	"PROD_LINE_TEAM_DESC" NVARCHAR2(255), 
	"PROD_LINE_CD" NVARCHAR2(255), 
	"PROD_LINE_DESC" NVARCHAR2(255), 
	"PROD_GROUP_CD" NVARCHAR2(255), 
	"PROD_GROUP_DESC" NVARCHAR2(255), 
	"ITEM_STOCK_TYPE_CD" NVARCHAR2(255), 
	"ITEM_STOCK_TYPE_DESC" NVARCHAR2(255), 
	"ITEM_STATUS_CD" NVARCHAR2(255), 
	"ITEM_STATUS_DESC" NVARCHAR2(255), 
	"ITEM_GROUP_CD" NVARCHAR2(255), 
	"ITEM_GROUP_DESC" NVARCHAR2(255), 
	"ITEM_2_DESC" NVARCHAR2(255), 
	"SUB_PROD_LINE_TEAM_CD" NVARCHAR2(255), 
	"SUB_PROD_LINE_TEAM_DESC" NVARCHAR2(255), 
	"ITEM_BASE_UOM_CD" NVARCHAR2(255), 
	"GRS_PROD_TECH_CD" NVARCHAR2(255), 
	"GRS_PROD_TECH_DESC" NVARCHAR2(255), 
	"GRS_MAJOR_PROD_GROUP_CD" NVARCHAR2(255), 
	"GRS_MAJOR_PROD_GROUP_DESC" NVARCHAR2(255), 
	"SOLD_ITEM_CD" NVARCHAR2(255), 
	"READY_FOR_PRICING" NVARCHAR2(255), 
	"PRICING_SUB_GROUP" NVARCHAR2(255), 
	"PATTERN_GUM" NVARCHAR2(255), 
	"ITEM_SPEC" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_PFXITEMMASTER_SRC
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_PFXITEMMASTER_SRC" 
   (	"PRODUCT_ID" NVARCHAR2(255), 
	"SOLD_ITEM_DESC" NVARCHAR2(255), 
	"SOURCE_SYSTEM_CD" NVARCHAR2(255), 
	"SFDC_IDENTIFIER" NVARCHAR2(255), 
	"LAST_UPDATE" NVARCHAR2(255), 
	"PRICING_LOGIC" NVARCHAR2(255), 
	"SOURCE_SUB_SYSTEM_CD" NVARCHAR2(255), 
	"EXTRACT_ID" NVARCHAR2(255), 
	"SPEC_DESC" NVARCHAR2(255), 
	"SPEC_CD" NVARCHAR2(255), 
	"PROD_LINE_TEAM_CD" NVARCHAR2(255), 
	"PRESSURE_SENSITIVE" NVARCHAR2(255), 
	"PROD_LINE_TEAM_DESC" NVARCHAR2(255), 
	"PROD_LINE_CD" NVARCHAR2(255), 
	"PROD_LINE_DESC" NVARCHAR2(255), 
	"PROD_GROUP_CD" NVARCHAR2(255), 
	"PROD_GROUP_DESC" NVARCHAR2(255), 
	"ITEM_STOCK_TYPE_CD" NVARCHAR2(255), 
	"ITEM_STOCK_TYPE_DESC" NVARCHAR2(255), 
	"ITEM_STATUS_CD" NVARCHAR2(255), 
	"ITEM_STATUS_DESC" NVARCHAR2(255), 
	"ITEM_GROUP_CD" NVARCHAR2(255), 
	"ITEM_GROUP_DESC" NVARCHAR2(255), 
	"ITEM_2_DESC" NVARCHAR2(255), 
	"SUB_PROD_LINE_TEAM_CD" NVARCHAR2(255), 
	"SUB_PROD_LINE_TEAM_DESC" NVARCHAR2(255), 
	"ITEM_BASE_UOM_CD" NVARCHAR2(255), 
	"GRS_PROD_TECH_CD" NVARCHAR2(255), 
	"GRS_PROD_TECH_DESC" NVARCHAR2(255), 
	"GRS_MAJOR_PROD_GROUP_CD" NVARCHAR2(255), 
	"GRS_MAJOR_PROD_GROUP_DESC" NVARCHAR2(255), 
	"SOLD_ITEM_CD" NVARCHAR2(255), 
	"READY_FOR_PRICING" NVARCHAR2(255), 
	"PRICING_SUB_GROUP" NVARCHAR2(255), 
	"PATTERN_GUM" NVARCHAR2(255), 
	"ITEM_SPEC" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_M_TRANSFERPRICES
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_M_TRANSFERPRICES" 
   (	"SPEC" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_R_EBSINTERFACE
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_R_EBSINTERFACE" 
   (	"QUOTE" VARCHAR2(100 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"MESSAGE" VARCHAR2(200 BYTE), 
	"ITEM" VARCHAR2(20 BYTE), 
	"CUSTOMER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_R_EBSINVOICES
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_R_EBSINVOICES" 
   (	"SALES_INVOICE_NUMBER" NVARCHAR2(50), 
	"INVOICE_DATE" NVARCHAR2(50), 
	"SALES_INVOICE_DATA_SOURCE" NVARCHAR2(50), 
	"CUSTOMER_ACCOUNT_NUMBER" NVARCHAR2(50), 
	"CUSTOMER_ACCOUNT_NAME" NVARCHAR2(50), 
	"BILLED_PRODUCT_AMOUNT" NUMBER, 
	"INVOICED_QUANTITY" NUMBER, 
	"INVOICED_AMOUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_R_EBSITEMS
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_R_EBSITEMS" 
   (	"IO" VARCHAR2(20 BYTE), 
	"ITEM" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"UOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"ORDERABLE" VARCHAR2(20 BYTE), 
	"ORDER_FLAG" VARCHAR2(20 BYTE), 
	"ENABLED_FLAG" VARCHAR2(20 BYTE), 
	"CREATION_DATE" VARCHAR2(20 BYTE), 
	"LAST_UPDATE_DATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_R_EBSQUOTES
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_R_EBSQUOTES" 
   (	"QUOTE_ID" VARCHAR2(200 BYTE), 
	"ACCT_NUMB" VARCHAR2(50 BYTE), 
	"QUOTE_TYPE" VARCHAR2(50 BYTE), 
	"QUOTE_STATUS" VARCHAR2(50 BYTE), 
	"PROJ_NUM" VARCHAR2(100 BYTE), 
	"PROJ_NAME" VARCHAR2(100 BYTE), 
	"DOC_NAME" VARCHAR2(100 BYTE), 
	"STATUS_CODE" VARCHAR2(100 BYTE), 
	"LINE_NUMBER" NUMBER, 
	"ITEM" VARCHAR2(50 BYTE), 
	"PRICE" NUMBER, 
	"UOM" VARCHAR2(10 BYTE), 
	"START_DATE_ACTIVE" DATE, 
	"END_DATE_ACTIVE" DATE, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"FREIGHT_TERMS" VARCHAR2(50 BYTE), 
	"APPLY_QTY_BRK" VARCHAR2(50 BYTE), 
	"SHEETING_WAIVE" VARCHAR2(50 BYTE), 
	"WAIVE_MIN_FREIGHT" VARCHAR2(50 BYTE), 
	"TRIM_WAIVE" VARCHAR2(50 BYTE), 
	"TRIM_MAX" VARCHAR2(50 BYTE), 
	"QUOTE_COMMENT" VARCHAR2(200 BYTE), 
	"SHORT_ROLL_WAIVE" VARCHAR2(50 BYTE), 
	"CURRENCY" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_R_PFXINVOICESDM
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_R_PFXINVOICESDM" 
   (	"INVOICE_DT" NVARCHAR2(255), 
	"INVOICE_NUM_CD" NVARCHAR2(255), 
	"PRODUCT_ID" NUMBER, 
	"PRODUCT_LOCAL_AMT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_R_PFXINVOICESDS
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_R_PFXINVOICESDS" 
   (	"INVOICE_DT" NVARCHAR2(255), 
	"INVOICE_NUM_CD" NVARCHAR2(255), 
	"PRODUCT_ID" NUMBER, 
	"PRODUCT_LOCAL_AMT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_R_PFXITEMMASTER
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_R_PFXITEMMASTER" 
   (	"PRODUCT_ID" NVARCHAR2(255), 
	"SOLD_ITEM_DESC" NVARCHAR2(255), 
	"SOURCE_SYSTEM_CD" NVARCHAR2(255), 
	"SFDC_IDENTIFIER" NVARCHAR2(255), 
	"LAST_UPDATE" NVARCHAR2(255), 
	"PRICING_LOGIC" NVARCHAR2(255), 
	"SOURCE_SUB_SYSTEM_CD" NVARCHAR2(255), 
	"EXTRACT_ID" NVARCHAR2(255), 
	"SPEC_DESC" NVARCHAR2(255), 
	"SPEC_CD" NVARCHAR2(255), 
	"PROD_LINE_TEAM_CD" NVARCHAR2(255), 
	"PRESSURE_SENSITIVE" NVARCHAR2(255), 
	"PROD_LINE_TEAM_DESC" NVARCHAR2(255), 
	"PROD_LINE_CD" NVARCHAR2(255), 
	"PROD_LINE_DESC" NVARCHAR2(255), 
	"PROD_GROUP_CD" NVARCHAR2(255), 
	"PROD_GROUP_DESC" NVARCHAR2(255), 
	"ITEM_STOCK_TYPE_CD" NVARCHAR2(255), 
	"ITEM_STOCK_TYPE_DESC" NVARCHAR2(255), 
	"ITEM_STATUS_CD" NVARCHAR2(255), 
	"ITEM_STATUS_DESC" NVARCHAR2(255), 
	"ITEM_GROUP_CD" NVARCHAR2(255), 
	"ITEM_GROUP_DESC" NVARCHAR2(255), 
	"ITEM_2_DESC" NVARCHAR2(255), 
	"SUB_PROD_LINE_TEAM_CD" NVARCHAR2(255), 
	"SUB_PROD_LINE_TEAM_DESC" NVARCHAR2(255), 
	"ITEM_BASE_UOM_CD" NVARCHAR2(255), 
	"GRS_PROD_TECH_CD" NVARCHAR2(255), 
	"GRS_PROD_TECH_DESC" NVARCHAR2(255), 
	"GRS_MAJOR_PROD_GROUP_CD" NVARCHAR2(255), 
	"GRS_MAJOR_PROD_GROUP_DESC" NVARCHAR2(255), 
	"SOLD_ITEM_CD" NVARCHAR2(255), 
	"READY_FOR_PRICING" NVARCHAR2(255), 
	"PRICING_SUB_GROUP" NVARCHAR2(255), 
	"PATTERN_GUM" NVARCHAR2(255), 
	"ITEM_SPEC" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Table XXSO_R_PFXQUOTES
--------------------------------------------------------

  CREATE TABLE "SOBREGON"."XXSO_R_PFXQUOTES" 
   (	"CUSTOMER_ID" NVARCHAR2(255), 
	"ACTIVE" NVARCHAR2(255), 
	"QUOTE" NVARCHAR2(255), 
	"LAST_UPDATE_DATE" NVARCHAR2(255), 
	"QUOTETYPE" NVARCHAR2(255), 
	"QUOTESTATUS" NVARCHAR2(255), 
	"EFFECTIVEDATE" NVARCHAR2(255), 
	"EXPIRYDATE" NVARCHAR2(255), 
	"ORIGINALEXPIRATIONDATE" NVARCHAR2(255), 
	"CUSTOMERNUMBER" NVARCHAR2(255), 
	"CUSTOMERNAME" NVARCHAR2(255), 
	"ITEM" NVARCHAR2(255), 
	"SPECDESC" NVARCHAR2(255), 
	"PRICE" FLOAT(126), 
	"CURRENCY" NVARCHAR2(255), 
	"UOM" NVARCHAR2(255), 
	"PROJECTNUMBER" NVARCHAR2(255), 
	"PROJECTNAME" NVARCHAR2(255), 
	"BUSINESSUNIT" NVARCHAR2(255), 
	"PRICINGSUBGROUP" NVARCHAR2(255), 
	"NATIONALACCOUNTNUMBER" NVARCHAR2(255), 
	"ITEMTYPE" NVARCHAR2(255), 
	"SPECDESC2" NVARCHAR2(255), 
	"CUSTOMERTIERPERCENTAGE" FLOAT(126), 
	"QUOTEDISCOUNTPERCENTAGE" FLOAT(126), 
	"FREIGHTRATES" NVARCHAR2(255), 
	"FREIGHTTERMS" NVARCHAR2(255), 
	"QUOTECOMMENT" NVARCHAR2(255), 
	"MOQ" NVARCHAR2(255), 
	"APPLYQTYBREAKSTR" NVARCHAR2(255), 
	"SHORTROLLWAIVE" NVARCHAR2(255), 
	"TRIMWAVE" NVARCHAR2(255), 
	"SHEETINGWAIVE" NVARCHAR2(255), 
	"LIFECYCLEPHASE" NVARCHAR2(255), 
	"LENGTH" NVARCHAR2(255), 
	"TRIMMAX" FLOAT(126), 
	"SYSTEMADDEDDATE" NVARCHAR2(255), 
	"SYSTEMUPDATEREASON" NVARCHAR2(255), 
	"REASONFORMANUALPRICECHANGE" NVARCHAR2(255), 
	"LIFECYCLESTATUS" NVARCHAR2(255), 
	"QUOTEDESCRIPTION" NVARCHAR2(255), 
	"UPDATEONLYTHISCUSTOMER" NVARCHAR2(255), 
	"QUOTEUNIQUEID" NVARCHAR2(255), 
	"APPROVEDBY" NVARCHAR2(255), 
	"APPROVEDDATE" NVARCHAR2(255), 
	"NAME_WO_REVISION" NVARCHAR2(255), 
	"PRODUCTSTRATEGY" NVARCHAR2(255), 
	"LINEITEMID" NVARCHAR2(255), 
	"WAIVEMINFREIGHT" NVARCHAR2(255), 
	"ATTR#48" NVARCHAR2(255), 
	"ATTR#49" NVARCHAR2(255), 
	"ATTR#50" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
--------------------------------------------------------
--  DDL for Index XXSO_R_EBSINTERFACE_IDX1
--------------------------------------------------------

  CREATE INDEX "SOBREGON"."XXSO_R_EBSINTERFACE_IDX1" ON "SOBREGON"."XXSO_R_EBSINTERFACE" ("QUOTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOBREGON" ;
